<<<<<<<< HEAD:src/main/java/App.java
 

import game_parts.Game;
========
/*
 * This source file was generated by the Gradle 'init' task
 */
package org.mainPackage;
>>>>>>>> main:app/src/main/java/org/mainPackage/App.java

public class App {
    public String getGreeting() {
        return "fffffuck it!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
<<<<<<<< HEAD:src/main/java/App.java
        Game game = new Game();
        game.getClass();
========
>>>>>>>> main:app/src/main/java/org/mainPackage/App.java
    }
}
