/*
 * This source file was generated by the Gradle 'init' task
 */
package org.mainPackage;

import org.mainPackage.core.Game;

public class App {
    public String getGreeting() {
        return "fffffuck it!";
    }

    public static void main(String[] args) {
        Game game = new Game();
        game.start();
        System.out.println(new App().getGreeting());
    }
}
